devise を使ってユーザー認証を実装するの課題を作成
kotakawase/fjord-books_app pull request #3
Opened 2021-06-13 07:40 UTC by kawase-k

2021-06-16 04:47 UTC, komagata requested changes

2021-06-16 04:47 UTC, komagata commented on .gitignore
> +/app/assets/stylesheets/users.scss
こう言うのはignoreに入れるのではなく、単に削除しちゃってください〜

2021-06-16 04:47 UTC, komagata commented on Gemfile
> +  gem 'devise-i18n'
これはdevelopment環境だけでなく全ての環境で必要になると思います〜

2021-06-16 04:47 UTC, komagata commented on app/helpers/users_helper.rb
> +module UsersHelper
実装のないmoduleは不要なので削除しちゃってください〜

2021-06-16 04:47 UTC, komagata commented on config/locales/devise.en.yml
> +# Additional translations at https://github.com/heartcombo/devise/wiki/I18n
https://bootcamp.fjord.jp/practices/40#honest-mistake

こちらのよくあるミスにあるように、devise-i18nを使ってる場合はこのファイルは不要です〜

2021-06-17 07:05 UTC, kotakawase commented on config/locales/devise.en.yml
> +# Additional translations at https://github.com/heartcombo/devise/wiki/I18n
そうでした…。
削除しました！ありがとうございます🙏

2021-06-17 07:05 UTC, kawase-k commented on app/helpers/users_helper.rb
> +module UsersHelper
削除しました！

2021-06-17 07:05 UTC, kawase-k commented on Gemfile
> +  gem 'devise-i18n'
対応しました！

2021-06-17 07:05 UTC, kawase-k commented on .gitignore
> +/app/assets/stylesheets/users.scss
対応しました！
今回、testディレクトリは消してしまったのですが問題ないのでしょうか？

2021-06-17 12:37 UTC, komagata requested changes

2021-06-17 12:37 UTC, komagata commented on app/views/users/index.html.erb
> +<%= link_to t('views.common.back'), :back %>
最終行に改行がないようです〜

2021-06-17 12:37 UTC, komagata commented on config/locales/devise.views.ja.yml
> +ja:
devise-i18nを使ってる場合はこのファイルは不要です〜

2021-06-18 05:47 UTC, kawase-k commented on app/views/users/index.html.erb
> +<%= link_to t('views.common.back'), :back %>
改行を追加しました！

2021-06-18 05:48 UTC, kawase-k commented on config/locales/devise.views.ja.yml
> +ja:
すみません🙏削除しておきました！

2021-06-21 03:40 UTC, komagata commented on .gitignore
> +/app/assets/stylesheets/users.scss
今回のプラクティスでは不要ですので消して大丈夫ですが、基本的にはtestは必ず書くので普通のプロジェクトでは消さないという感じです〜

2021-06-21 03:41 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-06-21 07:03 UTC, kawase-k commented on .gitignore
> +/app/assets/stylesheets/users.scss
分かりました！👌

2021-06-24 02:25 UTC, merged