Railsでテストを書くの課題を作成
kotakawase/fjord-books_app pull request #7
Opened 2021-07-01 17:41 UTC by kawase-k

2021-07-06 15:15 UTC, komagata requested changes

2021-07-06 15:15 UTC, komagata commented on test/fixtures/relationships.yml
> +# one:
過去の履歴は全てgitに保存されているので、不要な場合はコメントアウトして残さず削除するようにしてください〜

2021-07-06 15:15 UTC, komagata commented on test/models/user_test.rb
>  class UserTest < ActiveSupport::TestCase
基本的にはmodelは自分で実装したメソッドには最低一つはテストを実装してみてください〜
いくつか足りないようです〜。

2021-07-06 15:15 UTC, komagata commented on test/system/books_test.rb
> +    # , match: :first
gitにコードの履歴は全て残っているので不要なコードはコメントで残さず削除しちゃってください〜

2021-07-09 13:04 UTC, kawase-k commented on test/system/books_test.rb
> +    # , match: :first
確認不足でした🙏
コメントは削除しておきました！

2021-07-09 13:04 UTC, kawase-k commented on test/models/user_test.rb
>  class UserTest < ActiveSupport::TestCase
`followed_by`メソッドの追加をしてみました！

2021-07-09 13:04 UTC, kawase-k commented on test/fixtures/relationships.yml
> +# one:
すみません🙏
削除しておきました！

2021-07-09 14:23 UTC, komagata requested changes

2021-07-09 14:23 UTC, komagata commented on test/models/user_test.rb
>  class UserTest < ActiveSupport::TestCase
`following?`のテストが無いようです。
ほかにも自分がモデルに実装していてテストのないメソッドがないかどうか全部見直してみてください～

2021-07-10 06:01 UTC, kawase-k commented on test/models/user_test.rb
>  class UserTest < ActiveSupport::TestCase
`following?`, `followings`, `followers`のテストを追加しました！！

2021-07-10 06:09 UTC, komagata requested changes

2021-07-10 06:09 UTC, komagata commented on test/models/user_test.rb
> +    assert @she.valid?
validかどうかはこのメソッドで確かめるポイントではないとおもうので調べなくてもいいと思います～

2021-07-10 07:09 UTC, kawase-k commented on test/models/user_test.rb
> +    assert @she.valid?
## 質問
確認させてください！
このメソッドとは`followings`メソッドのみを指しているのでしょうか？

## 自分の認識

僕がvalidで確認していた理由は、単純にUserオブジェクトをsetupで作っていたから書いていただけでした😅
しかし今回のコメントで、モデルレベルではUserにバリデーションが追加されていないので確かに書く必要はないと思いました。

ですが、test/models/report_test.rbに書いてあるReportオブジェクトに対するvalidはいるのかなと思いました。
以下のコードにもありますがモデルレベルでバリデーションが行われているため。

```ruby
# app/models/reporst.rb
class Report < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true

  def editable?(target_user)
    user == target_user
  end

  def created_on
    created_at.to_date
  end
end
```

> validates :title, presence: true 
> validates :content, presence: true

なので、Userに対するvalidは削除してReportのvalidは残しておいた方がいいのかなと思っております。
誤りがあれば教えてください〜🙏

2021-07-12 05:54 UTC, komagata commented on test/models/user_test.rb
> +    assert @she.valid?
validationの機能はrailsの機能で、そちらはそちらでテストが書いてあるので、自分で実装したメソッドのテストだけで大丈夫です。

> このメソッドとはfollowingsメソッドのみを指しているのでしょうか？

他にもたくさんあります。全てです〜

2021-07-13 00:56 UTC, kawase-k commented on test/models/user_test.rb
> +    assert @she.valid?
分かりました！！

> 他にもたくさんあります。全てです〜

ありがとうございます🙏
こちら修正しました！

2021-07-13 04:42 UTC, komagata requested changes

2021-07-13 04:42 UTC, komagata commented on test/models/report_test.rb
> +    assert @report.created_on
ここは、両方`nil`じゃないことを確認するためって感じですかね？（それがすごく良いことだと思います！）

nilじゃないことを確かめているのであれば、

```
assert @report.created_on.present?
```

とかの方が意図が読む人に伝わりやすいかもです〜

2021-07-14 04:29 UTC, kawase-k commented on test/models/report_test.rb
> +    assert @report.created_on
おそらくそういった認識でテストを書いていたのだと思うのですが、今思い返すと自分も分かりづらかったです。

確かに値の有無を確認した方がいいですね😂
上記のコードに修正をしてみました！アドバイスありがとうございます〜！！

2021-07-15 06:22 UTC, komagata requested changes

2021-07-15 06:22 UTC, komagata commented on test/system/reports_test.rb
> +    page.accept_confirm do
```suggestion
    accept_confirm do
```

確かこれで行けたと思います〜

2021-07-16 02:00 UTC, kawase-k commented on test/system/reports_test.rb
> +    page.accept_confirm do
ありがとうございます！修正しておきました👌

参考: [Method: Capybara::Session#accept_confirm](https://www.rubydoc.info/github/jnicklas/capybara/Capybara/Session:accept_confirm)

2021-07-16 04:55 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

2021-07-18 03:24 UTC, merged